# Generated by Django 4.2.11 on 2024-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_transaction_date_remove_transaction_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
